CREATE TABLE CONSOMMATION_S(
       EmailConso VARCHAR(320),
       ID_Service NUMERIC(6),
       DateDeb TIMESTAMP NOT NULL,
       DateFin TIMESTAMP NOT NULL,
       CONSTRAINT PK_ConsoS PRIMARY KEY(EmailConso,ID_Service,DateDeb,DateFin),
       CONSTRAINT FK_Conso2 FOREIGN KEY(EmailConso) REFERENCES MEMBRE(Email),
       CONSTRAINT FK_Service FOREIGN KEY(ID_Service) REFERENCES SERVICE(ID_Service)
);
