CREATE TABLE CONSOMMATION_B(
       EmailConso VARCHAR(320),
       ID_Bien NUMERIC(6),
       DateDeb TIMESTAMP NOT NULL,
       DateFin TIMESTAMP NOT NULL,
       CONSTRAINT PK_ConsoB PRIMARY KEY(EmailConso,ID_Bien,DateDeb,DateFin),
       CONSTRAINT FK_Conso FOREIGN KEY(EmailConso) REFERENCES MEMBRE(Email),
       CONSTRAINT FK_Bien FOREIGN KEY(ID_Bien) REFERENCES BIEN(ID_Bien)
);
